<?php

// Prevent direct file access.
defined( 'ABSPATH' ) || die;

/**
 * Adds settings page.
 *
 * Original code generated by the WordPress Option Page generator:
 * @link http://jeremyhixon.com/wp-tools/option-page/
 */
class Mai_Publisher_Settings_Categories {
	/**
	 * Construct the class.
	 */
	function __construct() {
		$this->hooks();
	}

	/**
	 * Add hooks.
	 *
	 * @since 0.1.0
	 *
	 * @return void
	 */
	function hooks() {
		add_action( 'admin_menu', [ $this, 'add_menu_item' ], 12 );
	}

	/**
	 * Adds menu item for settings page.
	 *
	 * @since 0.1.0
	 *
	 * @return void
	 */
	function add_menu_item() {
		add_submenu_page(
			'edit.php?post_type=mai_ad',
			__( 'IAB Tech Lab Taxonomy Mapping', 'mai-publisher' ), // page_title
			__( 'Categories', 'mai-publisher' ), // menu_title
			'manage_options', // capability
			'categories', // menu_slug
			[ $this, 'add_content' ], // callback
		);
	}

	/**
	 * Adds setting page content.
	 *
	 * @since 0.1.0
	 *
	 * @return void
	 */
	function add_content() {
		echo '<div class="wrap">';
			printf( '<h2>%s</h2>', __( 'Categories', 'mai-publisher' ) );

			// Get the CSV file as an array.
			$file  = MAI_PUBLISHER_DIR . 'assets/csv/content-taxonomies.csv';
			$array = array_map( 'str_getcsv', file( $file ) );

			// Remove two rows (headers).
			array_shift( $array );
			array_shift( $array );

			// Setup taxonomies.
			$taxonomies = [];

			// Loop through each row.
			foreach ( $array as $data ) {
				$id     = $data[0];
				$parent = $data[1];
				$name   = $data[2];
				$tiers  = implode( ' / ', array_filter( array_unique( [ $data[3], $data[4], $data[5], $data[6], $name ] ) ) );
				$ext    = $data[7];

				// Add to taxonomies array.
				$taxonomies[ $id ] = $tiers;
			}

			// Render.
			echo '<textarea rows="10" cols="1" style="width:100%;height:90vh;background:white;" readonly>';
				echo '['. "\r\n";
					foreach ( $taxonomies as $key => $value ) {
						printf( "%s`%s` => `%s`,%s", "\t", $key, $value, "\r\n" );
					}
				echo '];';
				echo "\r\n";
			echo '</textarea>';
		echo '</div>';
	}

	function get_array_html( $array, $indent = "\t" ) {
		$html = '';

		foreach ( $array as $key => $value ) {
			$html .= "{$indent}'{$key}' => '{$value}'," . "\r\n";
		}

		return $html;
	}
}
